import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'animate.css';
import { Toaster } from "@/components/ui/sonner"
import {
  ClerkProvider
} from '@clerk/nextjs'
import Navbar from "./_component/Navbar";
import DataProvider from "./DataProvider";
<script src="https://checkout.razorpay.com/v1/checkout.js" async></script>
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Synvue.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider><html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <DataProvider>
        
      <Navbar/>
        {children}</DataProvider>
        <Toaster />
      </body>
    </html></ClerkProvider>
    
  );
}
